Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
